"""
Create the main forest plot for DAG-guided backdoor causal effects.

This script reads the unified result table generated by:
    scripts/01_run_backdoor_analysis.py

Default input:
    results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv

Default outputs:
    results/figures/Figure_Backdoor_ForestPlot_perSD.png
    results/figures/Figure_Backdoor_ForestPlot_perSD.pdf

Example:
    python code/dowhy/02_make_main_forest_plot.py

Or:
    python code/dowhy/02_make_main_forest_plot.py \
        --result-csv results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv \
        --out-dir results/figures
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch


# =============================================================================
# Helper functions
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create the main forest plot for backdoor causal effect estimates."
    )
    parser.add_argument(
        "--result-csv",
        type=Path,
        default=Path("results") / "dowhy" / "backdoor_results_perSD_with_CI_and_refuters.csv",
        help="Path to the unified backdoor result CSV generated by 01_run_backdoor_analysis.py.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results") / "figures",
        help="Directory for output figures.",
    )
    parser.add_argument(
        "--out-name",
        type=str,
        default="Figure_Backdoor_ForestPlot_perSD",
        help="Output figure filename without extension.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Backdoor Causal Effects of DXA-Derived Bone Features on Hip Fracture",
        help="Figure title.",
    )
    parser.add_argument(
        "--fig-width",
        type=float,
        default=11.0,
        help="Figure width in inches.",
    )
    parser.add_argument(
        "--row-height",
        type=float,
        default=0.45,
        help="Figure height per row in inches.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Resolution for PNG output.",
    )
    parser.add_argument(
        "--no-value-labels",
        action="store_true",
        help="Do not display numeric estimate and 95% CI labels next to points.",
    )
    parser.add_argument(
        "--sort-by",
        choices=["absolute_effect", "family_then_absolute_effect", "input_order"],
        default="absolute_effect",
        help="Sorting rule for plotting features.",
    )
    return parser.parse_args()


def validate_columns(df: pd.DataFrame, required_cols: list[str]) -> None:
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(
            "The following required columns are missing from the result table:\n"
            + "\n".join(f"  - {col}" for col in missing)
        )


def classify_family(x_name: str) -> str:
    x_low = str(x_name).lower()
    if "t-score" in x_low:
        return "T-score"
    if "bmd" in x_low:
        return "BMD"
    if "bmc" in x_low:
        return "BMC"
    return "Other"


def shorten_feature_label(x_name: str) -> str:
    """Convert original feature names into compact plot labels."""
    x_low = str(x_name).lower()

    if "neck" in x_low:
        region = "Femoral neck"
    elif "total" in x_low:
        region = "Total femur"
    elif "troch" in x_low:
        region = "Trochanter"
    elif "wards" in x_low:
        region = "Ward's region"
    elif "shaft" in x_low:
        region = "Femoral shaft"
    elif "pelvis" in x_low:
        region = "Pelvis"
    else:
        region = "Other region"

    if "t-score" in x_low:
        metric = "T-score"
    elif "bmd" in x_low:
        metric = "BMD"
    elif "bmc" in x_low:
        metric = "BMC"
    else:
        metric = "Other metric"

    return f"{region} {metric}"


def prepare_plot_dataframe(df: pd.DataFrame, sort_by: str) -> pd.DataFrame:
    required_cols = [
        "X_variable",
        "estimate_perSD",
        "CI95_low_perSD",
        "CI95_high_perSD",
    ]
    validate_columns(df, required_cols)

    plot_df = df.copy()

    if "family" not in plot_df.columns:
        plot_df["family"] = plot_df["X_variable"].apply(classify_family)

    plot_df = plot_df[
        ["X_variable", "family", "estimate_perSD", "CI95_low_perSD", "CI95_high_perSD"]
    ].copy()

    numeric_cols = ["estimate_perSD", "CI95_low_perSD", "CI95_high_perSD"]
    for col in numeric_cols:
        plot_df[col] = pd.to_numeric(plot_df[col], errors="coerce")

    plot_df = plot_df.dropna(subset=numeric_cols).copy()
    if plot_df.empty:
        raise ValueError("No valid rows remain after dropping missing estimate or CI values.")

    plot_df["label"] = plot_df["X_variable"].apply(shorten_feature_label)
    plot_df["abs_estimate_perSD"] = plot_df["estimate_perSD"].abs()

    if sort_by == "absolute_effect":
        plot_df = plot_df.sort_values("abs_estimate_perSD", ascending=False)
    elif sort_by == "family_then_absolute_effect":
        family_order = {"BMD": 0, "T-score": 1, "BMC": 2, "Other": 3}
        plot_df["family_order"] = plot_df["family"].map(family_order).fillna(99)
        plot_df = plot_df.sort_values(
            ["family_order", "abs_estimate_perSD"],
            ascending=[True, False],
        )
        plot_df = plot_df.drop(columns=["family_order"])
    elif sort_by == "input_order":
        plot_df = plot_df.reset_index(drop=True)

    # Reverse row order so the first row appears at the top of the horizontal plot.
    plot_df = plot_df.iloc[::-1].reset_index(drop=True)

    return plot_df


def create_forest_plot(
    plot_df: pd.DataFrame,
    out_dir: Path,
    out_name: str,
    title: str,
    fig_width: float,
    row_height: float,
    dpi: int,
    show_value_labels: bool = True,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    color_map = {
        "BMC": "#f4a6a6",
        "BMD": "#8ecae6",
        "T-score": "#a8ddb5",
        "Other": "#cccccc",
    }

    point_colors = plot_df["family"].map(color_map).fillna(color_map["Other"]).tolist()

    x = plot_df["estimate_perSD"].to_numpy(dtype=float)
    lo = plot_df["CI95_low_perSD"].to_numpy(dtype=float)
    hi = plot_df["CI95_high_perSD"].to_numpy(dtype=float)

    xerr_left = x - lo
    xerr_right = hi - x

    y = np.arange(len(plot_df))
    fig_height = max(6.0, row_height * len(plot_df))

    plt.figure(figsize=(fig_width, fig_height))

    for i in range(len(plot_df)):
        plt.errorbar(
            x[i],
            y[i],
            xerr=np.array([[xerr_left[i]], [xerr_right[i]]]),
            fmt="o",
            color=point_colors[i],
            ecolor=point_colors[i],
            elinewidth=2,
            capsize=3,
            markersize=6,
        )

    plt.axvline(0, linestyle="--", color="black", linewidth=1)

    plt.yticks(y, plot_df["label"].values, fontsize=10)
    plt.xlabel("Causal effect per SD increase (95% CI)", fontsize=12)
    plt.ylabel("DXA-derived bone feature", fontsize=12)
    plt.title(title, fontsize=14)

    if show_value_labels:
        finite_x = x[np.isfinite(x)]
        x_range = np.nanmax(np.abs(finite_x)) if len(finite_x) > 0 else 1.0
        offset = 0.02 * x_range if x_range > 0 else 0.001

        for i, val in enumerate(x):
            label = f"{val:.4f} [{lo[i]:.4f}, {hi[i]:.4f}]"
            if val >= 0:
                plt.text(val + offset, y[i], label, va="center", fontsize=8)
            else:
                plt.text(val - offset, y[i], label, va="center", ha="right", fontsize=8)

    legend_elements = [
        Patch(facecolor=color_map["BMC"], label="BMC"),
        Patch(facecolor=color_map["BMD"], label="BMD"),
        Patch(facecolor=color_map["T-score"], label="T-score"),
    ]
    plt.legend(handles=legend_elements, title="Feature family", loc="lower right")

    plt.tight_layout()

    png_path = out_dir / f"{out_name}.png"
    pdf_path = out_dir / f"{out_name}.pdf"

    plt.savefig(png_path, dpi=dpi, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    print(f"[OK] Saved PNG: {png_path}")
    print(f"[OK] Saved PDF: {pdf_path}")


# =============================================================================
# Main workflow
# =============================================================================

def main() -> None:
    args = parse_args()

    if not args.result_csv.exists():
        raise FileNotFoundError(
            f"Result CSV not found: {args.result_csv}\n"
            "Please run scripts/01_run_backdoor_analysis.py first, "
            "or provide --result-csv with the correct path."
        )

    df = pd.read_csv(args.result_csv)
    df.columns = df.columns.astype(str).str.strip()

    print(f"[INFO] Loaded result table: {args.result_csv}")
    print(f"[INFO] Result shape: {df.shape}")

    plot_df = prepare_plot_dataframe(df, sort_by=args.sort_by)

    print(f"[INFO] Number of features in forest plot: {len(plot_df)}")

    create_forest_plot(
        plot_df=plot_df,
        out_dir=args.out_dir,
        out_name=args.out_name,
        title=args.title,
        fig_width=args.fig_width,
        row_height=args.row_height,
        dpi=args.dpi,
        show_value_labels=not args.no_value_labels,
    )


if __name__ == "__main__":
    main()
