"""
Create the DoWhy refutation comparison figure.

This script reads the unified result table generated by:
    scripts/01_run_backdoor_analysis.py

It compares:
    1. Main backdoor estimate per SD
    2. Placebo treatment refuter new effect per SD
    3. Random common cause refuter new effect per SD
    4. Optional unobserved common cause sensitivity result, if available

Default input:
    results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv

Default outputs:
    results/figures/Figure_Refutation_Comparison_perSD.png
    results/figures/Figure_Refutation_Comparison_perSD.pdf

Example:
    python scripts/03_make_refutation_figure.py

Or:
    python scripts/03_make_refutation_figure.py \
        --result-csv results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv \
        --out-dir results/figures
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Helper functions
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create the DoWhy refutation comparison figure."
    )
    parser.add_argument(
        "--result-csv",
        type=Path,
        default=Path("results") / "dowhy" / "backdoor_results_perSD_with_CI_and_refuters.csv",
        help="Path to the unified backdoor result CSV generated by 01_run_backdoor_analysis.py.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results") / "figures",
        help="Directory for output figures.",
    )
    parser.add_argument(
        "--out-name",
        type=str,
        default="Figure_Refutation_Comparison_perSD",
        help="Output figure filename without extension.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="DoWhy Refutation Comparison for Backdoor Estimates",
        help="Figure title.",
    )
    parser.add_argument(
        "--fig-width",
        type=float,
        default=12.0,
        help="Figure width in inches.",
    )
    parser.add_argument(
        "--row-height",
        type=float,
        default=0.45,
        help="Figure height per row in inches.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Resolution for PNG output.",
    )
    parser.add_argument(
        "--sort-by",
        choices=["absolute_effect", "family_then_absolute_effect", "input_order"],
        default="absolute_effect",
        help="Sorting rule for plotting features.",
    )
    parser.add_argument(
        "--include-unobserved",
        action="store_true",
        help=(
            "Include unobserved common cause sensitivity result if the column "
            "unobserved_cc_new_effect_perSD exists and contains valid values."
        ),
    )
    return parser.parse_args()


def validate_columns(df: pd.DataFrame, required_cols: list[str]) -> None:
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(
            "The following required columns are missing from the result table:\n"
            + "\n".join(f"  - {col}" for col in missing)
        )


def classify_family(x_name: str) -> str:
    x_low = str(x_name).lower()
    if "t-score" in x_low:
        return "T-score"
    if "bmd" in x_low:
        return "BMD"
    if "bmc" in x_low:
        return "BMC"
    return "Other"


def shorten_feature_label(x_name: str) -> str:
    """Convert original feature names into compact plot labels."""
    x_low = str(x_name).lower()

    if "neck" in x_low:
        region = "Femoral neck"
    elif "total" in x_low:
        region = "Total femur"
    elif "troch" in x_low:
        region = "Trochanter"
    elif "wards" in x_low:
        region = "Ward's region"
    elif "shaft" in x_low:
        region = "Femoral shaft"
    elif "pelvis" in x_low:
        region = "Pelvis"
    else:
        region = "Other region"

    if "t-score" in x_low:
        metric = "T-score"
    elif "bmd" in x_low:
        metric = "BMD"
    elif "bmc" in x_low:
        metric = "BMC"
    else:
        metric = "Other metric"

    return f"{region} {metric}"


def prepare_plot_dataframe(
    df: pd.DataFrame,
    sort_by: str,
    include_unobserved: bool,
) -> tuple[pd.DataFrame, list[str], list[str]]:
    required_cols = [
        "X_variable",
        "estimate_perSD",
        "placebo_new_effect_perSD",
        "random_cc_new_effect_perSD",
    ]
    validate_columns(df, required_cols)

    plot_df = df.copy()

    if "family" not in plot_df.columns:
        plot_df["family"] = plot_df["X_variable"].apply(classify_family)

    base_cols = [
        "X_variable",
        "family",
        "estimate_perSD",
        "placebo_new_effect_perSD",
        "random_cc_new_effect_perSD",
    ]

    method_cols = [
        "estimate_perSD",
        "placebo_new_effect_perSD",
        "random_cc_new_effect_perSD",
    ]
    method_labels = [
        "Original estimate",
        "Placebo treatment refuter",
        "Random common cause refuter",
    ]

    if include_unobserved and "unobserved_cc_new_effect_perSD" in plot_df.columns:
        unobserved_values = pd.to_numeric(
            plot_df["unobserved_cc_new_effect_perSD"],
            errors="coerce",
        )
        if unobserved_values.notna().any():
            base_cols.append("unobserved_cc_new_effect_perSD")
            method_cols.append("unobserved_cc_new_effect_perSD")
            method_labels.append("Unobserved common cause sensitivity")

    plot_df = plot_df[base_cols].copy()

    for col in method_cols:
        plot_df[col] = pd.to_numeric(plot_df[col], errors="coerce")

    plot_df = plot_df.dropna(subset=["estimate_perSD"]).copy()
    if plot_df.empty:
        raise ValueError("No valid rows remain after dropping missing original estimates.")

    plot_df["label"] = plot_df["X_variable"].apply(shorten_feature_label)
    plot_df["abs_estimate_perSD"] = plot_df["estimate_perSD"].abs()

    if sort_by == "absolute_effect":
        plot_df = plot_df.sort_values("abs_estimate_perSD", ascending=False)
    elif sort_by == "family_then_absolute_effect":
        family_order = {"BMD": 0, "T-score": 1, "BMC": 2, "Other": 3}
        plot_df["family_order"] = plot_df["family"].map(family_order).fillna(99)
        plot_df = plot_df.sort_values(
            ["family_order", "abs_estimate_perSD"],
            ascending=[True, False],
        )
        plot_df = plot_df.drop(columns=["family_order"])
    elif sort_by == "input_order":
        plot_df = plot_df.reset_index(drop=True)

    # Reverse row order so the first row appears at the top of the horizontal plot.
    plot_df = plot_df.iloc[::-1].reset_index(drop=True)

    return plot_df, method_cols, method_labels


def create_refutation_plot(
    plot_df: pd.DataFrame,
    method_cols: list[str],
    method_labels: list[str],
    out_dir: Path,
    out_name: str,
    title: str,
    fig_width: float,
    row_height: float,
    dpi: int,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    marker_styles = ["o", "s", "^", "D"]
    line_offsets = np.linspace(-0.25, 0.25, num=len(method_cols))

    y = np.arange(len(plot_df))
    fig_height = max(6.0, row_height * len(plot_df))

    plt.figure(figsize=(fig_width, fig_height))

    for idx, (col, label) in enumerate(zip(method_cols, method_labels)):
        x_values = plot_df[col].to_numpy(dtype=float)
        valid = np.isfinite(x_values)

        plt.plot(
            x_values[valid],
            y[valid] + line_offsets[idx],
            marker_styles[idx % len(marker_styles)],
            linestyle="None",
            markersize=6,
            label=label,
        )

    plt.axvline(0, linestyle="--", color="black", linewidth=1)

    plt.yticks(y, plot_df["label"].values, fontsize=10)
    plt.xlabel("Effect estimate per SD", fontsize=12)
    plt.ylabel("DXA-derived bone feature", fontsize=12)
    plt.title(title, fontsize=14)

    plt.legend(loc="lower right")
    plt.tight_layout()

    png_path = out_dir / f"{out_name}.png"
    pdf_path = out_dir / f"{out_name}.pdf"

    plt.savefig(png_path, dpi=dpi, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")
    plt.close()

    print(f"[OK] Saved PNG: {png_path}")
    print(f"[OK] Saved PDF: {pdf_path}")


# =============================================================================
# Main workflow
# =============================================================================

def main() -> None:
    args = parse_args()

    if not args.result_csv.exists():
        raise FileNotFoundError(
            f"Result CSV not found: {args.result_csv}\n"
            "Please run scripts/01_run_backdoor_analysis.py first, "
            "or provide --result-csv with the correct path."
        )

    df = pd.read_csv(args.result_csv)
    df.columns = df.columns.astype(str).str.strip()

    print(f"[INFO] Loaded result table: {args.result_csv}")
    print(f"[INFO] Result shape: {df.shape}")

    plot_df, method_cols, method_labels = prepare_plot_dataframe(
        df=df,
        sort_by=args.sort_by,
        include_unobserved=args.include_unobserved,
    )

    print(f"[INFO] Number of features in refutation plot: {len(plot_df)}")
    print(f"[INFO] Methods included: {', '.join(method_labels)}")

    create_refutation_plot(
        plot_df=plot_df,
        method_cols=method_cols,
        method_labels=method_labels,
        out_dir=args.out_dir,
        out_name=args.out_name,
        title=args.title,
        fig_width=args.fig_width,
        row_height=args.row_height,
        dpi=args.dpi,
    )


if __name__ == "__main__":
    main()
