"""
Create supplementary summary figures for DAG-guided backdoor causal effects.

This script combines the previous family summary, region summary, and heatmap scripts.

It reads the unified result table generated by:
    scripts/01_run_backdoor_analysis.py

Default input:
    results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv

Default outputs:
    results/figures/Figure_Family_Summary_meanAbsEffect_perSD.png
    results/figures/Figure_Family_Summary_meanAbsEffect_perSD.pdf
    results/figures/Figure_Region_Summary_meanAbsEffect_perSD.png
    results/figures/Figure_Region_Summary_meanAbsEffect_perSD.pdf
    results/figures/Figure_CausalEffect_Heatmap_perSD.png
    results/figures/Figure_CausalEffect_Heatmap_perSD.pdf

Also saves summary tables:
    results/tables/Table_Family_Summary_meanAbsEffect_perSD.csv
    results/tables/Table_Region_Summary_meanAbsEffect_perSD.csv
    results/tables/Table_CausalEffect_Heatmap_perSD.csv

Example:
    python scripts/04_make_summary_figures.py

Or:
    python scripts/04_make_summary_figures.py \
        --result-csv results/dowhy/backdoor_results_perSD_with_CI_and_refuters.csv \
        --fig-dir results/figures \
        --table-dir results/tables
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# Constants
# =============================================================================

FAMILY_ORDER = ["BMD", "T-score", "BMC"]
REGION_ORDER = ["Neck", "Total", "Troch", "Wards", "Shaft", "Pelvis"]

FAMILY_COLOR_MAP = {
    "BMC": "#f4a6a6",
    "BMD": "#8ecae6",
    "T-score": "#a8ddb5",
    "Other": "#cccccc",
}


# =============================================================================
# Helper functions
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create family summary, region summary, and heatmap figures."
    )
    parser.add_argument(
        "--result-csv",
        type=Path,
        default=Path("results") / "dowhy" / "backdoor_results_perSD_with_CI_and_refuters.csv",
        help="Path to the unified backdoor result CSV generated by 01_run_backdoor_analysis.py.",
    )
    parser.add_argument(
        "--fig-dir",
        type=Path,
        default=Path("results") / "figures",
        help="Directory for output figures.",
    )
    parser.add_argument(
        "--table-dir",
        type=Path,
        default=Path("results") / "tables",
        help="Directory for output summary tables.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Resolution for PNG output.",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Save PNG only and skip PDF output.",
    )
    return parser.parse_args()


def validate_columns(df: pd.DataFrame, required_cols: list[str]) -> None:
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(
            "The following required columns are missing from the result table:\n"
            + "\n".join(f"  - {col}" for col in missing)
        )


def classify_family(x_name: str) -> str:
    x_low = str(x_name).lower()
    if "t-score" in x_low:
        return "T-score"
    if "bmd" in x_low:
        return "BMD"
    if "bmc" in x_low:
        return "BMC"
    return "Other"


def classify_region(x_name: str) -> str:
    x_low = str(x_name).lower()
    if "neck" in x_low:
        return "Neck"
    if "total" in x_low:
        return "Total"
    if "troch" in x_low:
        return "Troch"
    if "wards" in x_low:
        return "Wards"
    if "shaft" in x_low:
        return "Shaft"
    if "pelvis" in x_low:
        return "Pelvis"
    return "Other"


def load_and_prepare_results(result_csv: Path) -> pd.DataFrame:
    if not result_csv.exists():
        raise FileNotFoundError(
            f"Result CSV not found: {result_csv}\n"
            "Please run scripts/01_run_backdoor_analysis.py first, "
            "or provide --result-csv with the correct path."
        )

    df = pd.read_csv(result_csv)
    df.columns = df.columns.astype(str).str.strip()

    validate_columns(df, ["X_variable", "estimate_perSD"])

    df["estimate_perSD"] = pd.to_numeric(df["estimate_perSD"], errors="coerce")
    df = df.dropna(subset=["estimate_perSD"]).copy()

    if "family" not in df.columns:
        df["family"] = df["X_variable"].apply(classify_family)
    if "region" not in df.columns:
        df["region"] = df["X_variable"].apply(classify_region)

    df["family"] = df["family"].astype(str)
    df["region"] = df["region"].astype(str)
    df["abs_estimate_perSD"] = df["estimate_perSD"].abs()

    return df


def save_current_figure(fig_dir: Path, out_name: str, dpi: int, save_pdf: bool) -> None:
    fig_dir.mkdir(parents=True, exist_ok=True)

    png_path = fig_dir / f"{out_name}.png"
    plt.savefig(png_path, dpi=dpi, bbox_inches="tight")
    print(f"[OK] Saved PNG: {png_path}")

    if save_pdf:
        pdf_path = fig_dir / f"{out_name}.pdf"
        plt.savefig(pdf_path, bbox_inches="tight")
        print(f"[OK] Saved PDF: {pdf_path}")

    plt.close()


# =============================================================================
# Summary table functions
# =============================================================================

def make_family_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df[df["family"].isin(FAMILY_ORDER)]
        .groupby("family", dropna=False)["abs_estimate_perSD"]
        .agg(["mean", "std", "count"])
        .reset_index()
        .rename(
            columns={
                "mean": "mean_abs_estimate_perSD",
                "std": "sd_abs_estimate_perSD",
                "count": "n_features",
            }
        )
    )

    summary["family"] = pd.Categorical(summary["family"], categories=FAMILY_ORDER, ordered=True)
    summary = summary.sort_values("family").reset_index(drop=True)
    return summary


def make_region_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df[df["region"].isin(REGION_ORDER)]
        .groupby("region", dropna=False)["abs_estimate_perSD"]
        .agg(["mean", "std", "count"])
        .reset_index()
        .rename(
            columns={
                "mean": "mean_abs_estimate_perSD",
                "std": "sd_abs_estimate_perSD",
                "count": "n_features",
            }
        )
    )

    summary["region"] = pd.Categorical(summary["region"], categories=REGION_ORDER, ordered=True)
    summary = summary.sort_values("region").reset_index(drop=True)
    return summary


def make_heatmap_table(df: pd.DataFrame) -> pd.DataFrame:
    heatmap_df = df[
        df["family"].isin(FAMILY_ORDER) & df["region"].isin(REGION_ORDER)
    ].copy()

    heatmap_table = (
        heatmap_df.groupby(["region", "family"], dropna=False)["estimate_perSD"]
        .mean()
        .reset_index()
        .pivot(index="region", columns="family", values="estimate_perSD")
    )

    heatmap_table = heatmap_table.reindex(index=REGION_ORDER, columns=FAMILY_ORDER)
    return heatmap_table


# =============================================================================
# Plot functions
# =============================================================================

def plot_family_summary(summary: pd.DataFrame, fig_dir: Path, dpi: int, save_pdf: bool) -> None:
    if summary.empty:
        print("[WARN] Family summary is empty. Skipping family summary figure.")
        return

    x = np.arange(len(summary))
    means = summary["mean_abs_estimate_perSD"].to_numpy(dtype=float)
    stds = summary["sd_abs_estimate_perSD"].fillna(0).to_numpy(dtype=float)
    labels = summary["family"].astype(str).to_numpy()
    colors = [FAMILY_COLOR_MAP.get(label, FAMILY_COLOR_MAP["Other"]) for label in labels]

    plt.figure(figsize=(7, 5))
    plt.bar(x, means, yerr=stds, capsize=5, color=colors)

    plt.xticks(x, labels, fontsize=11)
    plt.ylabel("Mean absolute causal effect per SD", fontsize=12)
    plt.xlabel("Feature family", fontsize=12)
    plt.title("Summary of Backdoor Effect Sizes by Feature Family", fontsize=14)

    ymax = np.nanmax(means + stds) if len(means) > 0 else 1.0
    offset = 0.02 * ymax if ymax > 0 else 0.001

    for i, value in enumerate(means):
        plt.text(i, value + offset, f"{value:.4f}", ha="center", va="bottom", fontsize=10)

    plt.tight_layout()
    save_current_figure(
        fig_dir=fig_dir,
        out_name="Figure_Family_Summary_meanAbsEffect_perSD",
        dpi=dpi,
        save_pdf=save_pdf,
    )


def plot_region_summary(summary: pd.DataFrame, fig_dir: Path, dpi: int, save_pdf: bool) -> None:
    if summary.empty:
        print("[WARN] Region summary is empty. Skipping region summary figure.")
        return

    x = np.arange(len(summary))
    means = summary["mean_abs_estimate_perSD"].to_numpy(dtype=float)
    stds = summary["sd_abs_estimate_perSD"].fillna(0).to_numpy(dtype=float)
    labels = summary["region"].astype(str).to_numpy()

    plt.figure(figsize=(8, 5))
    plt.bar(x, means, yerr=stds, capsize=5)

    plt.xticks(x, labels, fontsize=11)
    plt.ylabel("Mean absolute causal effect per SD", fontsize=12)
    plt.xlabel("Bone region", fontsize=12)
    plt.title("Summary of Backdoor Effect Sizes by Bone Region", fontsize=14)

    ymax = np.nanmax(means + stds) if len(means) > 0 else 1.0
    offset = 0.02 * ymax if ymax > 0 else 0.001

    for i, value in enumerate(means):
        plt.text(i, value + offset, f"{value:.4f}", ha="center", va="bottom", fontsize=10)

    plt.tight_layout()
    save_current_figure(
        fig_dir=fig_dir,
        out_name="Figure_Region_Summary_meanAbsEffect_perSD",
        dpi=dpi,
        save_pdf=save_pdf,
    )


def plot_heatmap(heatmap_table: pd.DataFrame, fig_dir: Path, dpi: int, save_pdf: bool) -> None:
    if heatmap_table.empty:
        print("[WARN] Heatmap table is empty. Skipping heatmap figure.")
        return

    data = heatmap_table.to_numpy(dtype=float)

    plt.figure(figsize=(7, 5.5))
    ax = plt.gca()

    im = ax.imshow(data, aspect="auto", cmap="RdBu_r")

    ax.set_xticks(np.arange(len(FAMILY_ORDER)))
    ax.set_yticks(np.arange(len(REGION_ORDER)))
    ax.set_xticklabels(FAMILY_ORDER, fontsize=11)
    ax.set_yticklabels(REGION_ORDER, fontsize=11)

    ax.set_xlabel("Feature family", fontsize=12)
    ax.set_ylabel("Bone region", fontsize=12)
    ax.set_title("Causal Effect Heatmap per SD", fontsize=14)

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            value = data[i, j]
            if np.isfinite(value):
                ax.text(j, i, f"{value:.4f}", ha="center", va="center", fontsize=10)

    colorbar = plt.colorbar(im, ax=ax)
    colorbar.set_label("Causal effect per SD", fontsize=11)

    plt.tight_layout()
    save_current_figure(
        fig_dir=fig_dir,
        out_name="Figure_CausalEffect_Heatmap_perSD",
        dpi=dpi,
        save_pdf=save_pdf,
    )


# =============================================================================
# Main workflow
# =============================================================================

def main() -> None:
    args = parse_args()

    args.fig_dir.mkdir(parents=True, exist_ok=True)
    args.table_dir.mkdir(parents=True, exist_ok=True)

    df = load_and_prepare_results(args.result_csv)

    print(f"[INFO] Loaded result table: {args.result_csv}")
    print(f"[INFO] Result shape after cleaning: {df.shape}")

    family_summary = make_family_summary(df)
    region_summary = make_region_summary(df)
    heatmap_table = make_heatmap_table(df)

    family_table_path = args.table_dir / "Table_Family_Summary_meanAbsEffect_perSD.csv"
    region_table_path = args.table_dir / "Table_Region_Summary_meanAbsEffect_perSD.csv"
    heatmap_table_path = args.table_dir / "Table_CausalEffect_Heatmap_perSD.csv"

    family_summary.to_csv(family_table_path, index=False, encoding="utf-8-sig")
    region_summary.to_csv(region_table_path, index=False, encoding="utf-8-sig")
    heatmap_table.to_csv(heatmap_table_path, encoding="utf-8-sig")

    print(f"[OK] Saved family summary table: {family_table_path}")
    print(f"[OK] Saved region summary table: {region_table_path}")
    print(f"[OK] Saved heatmap table: {heatmap_table_path}")

    save_pdf = not args.no_pdf

    plot_family_summary(family_summary, args.fig_dir, args.dpi, save_pdf)
    plot_region_summary(region_summary, args.fig_dir, args.dpi, save_pdf)
    plot_heatmap(heatmap_table, args.fig_dir, args.dpi, save_pdf)


if __name__ == "__main__":
    main()
