"""
Create 4x4 panel figures for CausalForestDML outputs.

This script collects per-treatment figures generated by:
    code/causalforestdml/01_run_causal_forest_dml.py

and combines them into all-treatment 4x4 panel figures.

Default input:
    results/causalforestdml/

Default outputs:
    results/causalforestdml/panels/

Example:
    python code/causalforestdml/02_make_panel_figures.py

Or:
    python code/causalforestdml/02_make_panel_figures.py \
        --input-dir results/causalforestdml \
        --out-dir results/causalforestdml/panels
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image


# =============================================================================
# Figure specifications
# =============================================================================

FIGURE_SPECS = [
    ("ATE_forest", "Figure_ATE_forest_singleT.png", "All Treatments - ATE Forest"),
    ("CATE_distribution", "Figure_CATE_distribution_perSD.png", "All Treatments - CATE Distribution"),
    ("Feature_importance", "Figure_feature_importance.png", "All Treatments - Feature Importance"),
    ("Subgroup_age", "Figure_CATE_subgroup_age.png", "All Treatments - Subgroup CATE by Age"),
    ("Subgroup_sex", "Figure_CATE_subgroup_sex.png", "All Treatments - Subgroup CATE by Sex"),
    ("Subgroup_BMI", "Figure_CATE_subgroup_BMI.png", "All Treatments - Subgroup CATE by BMI"),
    ("AgeSex_curve", "Figure_CATE_curve_AgeSex.png", "All Treatments - CATE Curve by Age and Sex"),
    ("Decile_summary", "Figure_CATE_decile_summary.png", "All Treatments - CATE Decile Summary"),
]


# =============================================================================
# Helper functions
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create 4x4 panel figures from per-treatment CausalForestDML outputs."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("results") / "causal_forest",
        help="Directory containing per-treatment output folders from 01_run_causal_forest_dml.py.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results") / "causal_forest" / "panels",
        help="Directory for all-treatment panel figures.",
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=None,
        help=(
            "Optional path to the all-treatment summary CSV used to order treatments. "
            "If not provided, the script looks for "
            "input-dir/CausalForestDML_all_treatments_summary.csv."
        ),
    )
    parser.add_argument(
        "--n-cols",
        type=int,
        default=4,
        help="Number of columns in the panel grid.",
    )
    parser.add_argument(
        "--n-rows",
        type=int,
        default=4,
        help="Number of rows in the panel grid.",
    )
    parser.add_argument(
        "--cell-width",
        type=float,
        default=4.8,
        help="Width of each panel cell in inches.",
    )
    parser.add_argument(
        "--cell-height",
        type=float,
        default=3.8,
        help="Height of each panel cell in inches.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Resolution for PNG output.",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Save PNG only and skip PDF output.",
    )
    return parser.parse_args()


def safe_name(value: str, max_len: int = 180) -> str:
    value = str(value).strip()
    value = re.sub(r'[\\/*?:"<>|]', "_", value)
    value = re.sub(r"\s+", "_", value)
    return value[:max_len]


def is_treatment_folder(folder_path: Path) -> bool:
    """
    A treatment folder is defined as one that contains summary_single_treatment.csv.
    """
    return (folder_path / "summary_single_treatment.csv").is_file()


def load_pil_image(image_path: Path):
    if not image_path.is_file():
        return None
    try:
        return Image.open(image_path).convert("RGB")
    except Exception:
        return None


def get_default_summary_csv(input_dir: Path) -> Path:
    return input_dir / "CausalForestDML_all_treatments_summary.csv"


def get_treatment_order(input_dir: Path, summary_csv: Path | None) -> list[str]:
    treatment_dirs = [
        item.name for item in input_dir.iterdir()
        if item.is_dir() and is_treatment_folder(item)
    ]

    if len(treatment_dirs) == 0:
        raise RuntimeError(
            "No treatment folders found in the input directory. "
            "Please run 01_run_causal_forest_dml.py first."
        )

    if summary_csv is not None and summary_csv.is_file():
        try:
            df = pd.read_csv(summary_csv)
            if "Treatment" in df.columns:
                ordered = []
                for treatment in df["Treatment"].astype(str).tolist():
                    folder_name = safe_name(treatment)
                    if folder_name in treatment_dirs:
                        ordered.append(folder_name)

                leftovers = [name for name in sorted(treatment_dirs) if name not in ordered]
                ordered.extend(leftovers)
                return ordered
        except Exception as exc:
            print(f"[WARN] Failed to use summary CSV ordering: {exc}")

    return sorted(treatment_dirs)


def build_grid_panel(
    treatment_folders: list[str],
    input_dir: Path,
    figure_filename: str,
    figure_title: str,
    out_png: Path,
    out_pdf: Path,
    n_rows: int,
    n_cols: int,
    cell_width: float,
    cell_height: float,
    dpi: int,
    save_pdf: bool,
) -> None:
    total_slots = n_rows * n_cols
    n_treatments = len(treatment_folders)

    if n_treatments > total_slots:
        raise ValueError(
            f"Found {n_treatments} treatments, but the panel grid only has "
            f"{total_slots} slots ({n_rows}x{n_cols}). Increase n_rows or n_cols."
        )

    fig_w = cell_width * n_cols
    fig_h = cell_height * n_rows

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(fig_w, fig_h))
    axes = np.atleast_1d(axes).flatten()

    for index in range(total_slots):
        ax = axes[index]

        if index < n_treatments:
            treatment_name = treatment_folders[index]
            image_path = input_dir / treatment_name / figure_filename
            image = load_pil_image(image_path)

            if image is not None:
                ax.imshow(image)
            else:
                ax.text(
                    0.5,
                    0.5,
                    f"Missing:\n{figure_filename}",
                    ha="center",
                    va="center",
                    fontsize=11,
                )

            ax.set_title(treatment_name, fontsize=10, pad=8)
        else:
            ax.axis("off")
            continue

        ax.set_xticks([])
        ax.set_yticks([])

    fig.suptitle(figure_title, fontsize=16, y=0.995)
    plt.tight_layout(rect=[0, 0, 1, 0.985])

    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, dpi=dpi, bbox_inches="tight")
    print(f"[OK] Saved PNG: {out_png}")

    if save_pdf:
        plt.savefig(out_pdf, bbox_inches="tight")
        print(f"[OK] Saved PDF: {out_pdf}")

    plt.close()


# =============================================================================
# Main workflow
# =============================================================================

def main() -> None:
    args = parse_args()

    input_dir = args.input_dir
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if not input_dir.exists():
        raise FileNotFoundError(
            f"Input directory not found: {input_dir}\n"
            "Please run 01_run_causal_forest_dml.py first, "
            "or provide the correct --input-dir."
        )

    summary_csv = args.summary_csv if args.summary_csv is not None else get_default_summary_csv(input_dir)

    treatment_folders = get_treatment_order(input_dir, summary_csv)

    print(f"[INFO] Input directory: {input_dir}")
    print(f"[INFO] Output directory: {out_dir}")
    print(f"[INFO] Number of treatment folders: {len(treatment_folders)}")
    print("[INFO] Treatment order:")
    for name in treatment_folders:
        print(f"  - {name}")

    save_pdf = not args.no_pdf

    for figure_key, figure_filename, figure_title in FIGURE_SPECS:
        out_png = out_dir / f"Panel_{figure_key}_4x4.png"
        out_pdf = out_dir / f"Panel_{figure_key}_4x4.pdf"

        print(f"\n[RUN] Building panel for: {figure_filename}")

        build_grid_panel(
            treatment_folders=treatment_folders,
            input_dir=input_dir,
            figure_filename=figure_filename,
            figure_title=figure_title,
            out_png=out_png,
            out_pdf=out_pdf,
            n_rows=args.n_rows,
            n_cols=args.n_cols,
            cell_width=args.cell_width,
            cell_height=args.cell_height,
            dpi=args.dpi,
            save_pdf=save_pdf,
        )

    print("[OK] Panel figure generation finished.")


if __name__ == "__main__":
    main()
